/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from "zod";

export const deleteApiCustomerLinksIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Ссылка удалена
 */
export const deleteApiCustomerLinksId204Schema = z.any();

/**
 * @description Неверные входные данные
 */
export const deleteApiCustomerLinksId400Schema = z.any();

/**
 * @description Ссылка не найдена
 */
export const deleteApiCustomerLinksId404Schema = z.any();

export const deleteApiCustomerLinksIdMutationResponseSchema = z.lazy(() => deleteApiCustomerLinksId204Schema);
