/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from "zod";

export const getApiCustomerLinksIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Объект ссылки
 */
export const getApiCustomerLinksId200Schema = z.object({
  id: z.string(),
  userId: z.string(),
  status: z.enum(["ENABLE", "DISABLE"]),
  name: z.string(),
  token: z.string(),
  redirectUrl: z.string(),
  redirectCount: z.number(),
  updatedAt: z.string(),
  createdAt: z.string(),
  url: z.string(),
});

/**
 * @description Неверные входные данные
 */
export const getApiCustomerLinksId400Schema = z.any();

/**
 * @description Ссылка не найдена
 */
export const getApiCustomerLinksId404Schema = z.any();

export const getApiCustomerLinksIdQueryResponseSchema = z.lazy(() => getApiCustomerLinksId200Schema);
