/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from "zod";

/**
 * @description Объект ссылки
 */
export const postApiCustomerLinks200Schema = z.object({
  id: z.string(),
  userId: z.string(),
  status: z.enum(["ENABLE", "DISABLE"]),
  name: z.string(),
  token: z.string(),
  redirectUrl: z.string(),
  redirectCount: z.number(),
  updatedAt: z.string(),
  createdAt: z.string(),
  url: z.string(),
});

/**
 * @description Неверные входные данные
 */
export const postApiCustomerLinks400Schema = z.any();

export const postApiCustomerLinksMutationRequestSchema = z.object({
  name: z.string(),
  redirectUrl: z.string(),
});

export const postApiCustomerLinksMutationResponseSchema = z.lazy(() => postApiCustomerLinks200Schema);
