/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from "zod";

export const putApiCustomerLinksIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description Объект ссылки
 */
export const putApiCustomerLinksId200Schema = z.object({
  id: z.string(),
  userId: z.string(),
  status: z.enum(["ENABLE", "DISABLE"]),
  name: z.string(),
  token: z.string(),
  redirectUrl: z.string(),
  redirectCount: z.number(),
  updatedAt: z.string(),
  createdAt: z.string(),
  url: z.string(),
});

/**
 * @description Неверные входные данные
 */
export const putApiCustomerLinksId400Schema = z.any();

/**
 * @description Ссылка не найдена
 */
export const putApiCustomerLinksId404Schema = z.any();

export const putApiCustomerLinksIdMutationRequestSchema = z.object({
  name: z.string(),
});

export const putApiCustomerLinksIdMutationResponseSchema = z.lazy(() => putApiCustomerLinksId200Schema);
