/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiCustomerLinksIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Ссылка удалена
 */
export type DeleteApiCustomerLinksId204 = any;

/**
 * @description Неверные входные данные
 */
export type DeleteApiCustomerLinksId400 = any;

/**
 * @description Ссылка не найдена
 */
export type DeleteApiCustomerLinksId404 = any;

export type DeleteApiCustomerLinksIdMutationResponse = DeleteApiCustomerLinksId204;

export type DeleteApiCustomerLinksIdMutation = {
  Response: DeleteApiCustomerLinksId204;
  PathParams: DeleteApiCustomerLinksIdPathParams;
  Errors: DeleteApiCustomerLinksId400 | DeleteApiCustomerLinksId404;
};
