/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiCustomerLinksQueryParams = {
  /**
   * @minLength 0
   * @maxLength 100
   * @type number
   */
  limit?: number | null;
  /**
   * @minLength 0
   * @maxLength 9007199254740991
   * @type number
   */
  offset?: number | null;
};

export type ItemsStatusEnum = "ENABLE" | "DISABLE";

/**
 * @description Список ссылок
 */
export type GetApiCustomerLinks200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    userId: string;
    /**
     * @type string
     */
    status: ItemsStatusEnum;
    /**
     * @type string
     */
    name: string;
    /**
     * @type string
     */
    token: string;
    /**
     * @type string
     */
    redirectUrl: string;
    /**
     * @type number
     */
    redirectCount: number;
    /**
     * @type string
     */
    updatedAt: string;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    url: string;
  }[];
  /**
   * @minLength 0
   * @maxLength 100
   * @type number
   */
  limit: number | null;
  /**
   * @minLength 0
   * @maxLength 9007199254740991
   * @type number
   */
  offset: number | null;
  /**
   * @type number
   */
  total: number | null;
};

/**
 * @description Неверные входные данные
 */
export type GetApiCustomerLinks400 = any;

export type GetApiCustomerLinksQueryResponse = GetApiCustomerLinks200;

export type GetApiCustomerLinksQuery = {
  Response: GetApiCustomerLinks200;
  QueryParams: GetApiCustomerLinksQueryParams;
  Errors: GetApiCustomerLinks400;
};
