/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostApiCustomerLinks200StatusEnum = "ENABLE" | "DISABLE";

/**
 * @description Объект ссылки
 */
export type PostApiCustomerLinks200 = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  userId: string;
  /**
   * @type string
   */
  status: PostApiCustomerLinks200StatusEnum;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  token: string;
  /**
   * @type string
   */
  redirectUrl: string;
  /**
   * @type number
   */
  redirectCount: number;
  /**
   * @type string
   */
  updatedAt: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  url: string;
};

/**
 * @description Неверные входные данные
 */
export type PostApiCustomerLinks400 = any;

export type PostApiCustomerLinksMutationRequest = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  redirectUrl: string;
};

export type PostApiCustomerLinksMutationResponse = PostApiCustomerLinks200;

export type PostApiCustomerLinksMutation = {
  Response: PostApiCustomerLinks200;
  Request: PostApiCustomerLinksMutationRequest;
  Errors: PostApiCustomerLinks400;
};
